# Generated by Django 5.1.4 on 2025-01-02 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0006_member_last_login_alter_member_email_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='member',
            table='member_members',
        ),
    ]
