# Generated by Django 5.1.4 on 2025-01-02 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0007_alter_member_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='member',
            table='members_member',
        ),
    ]
