# Generated by Django 5.1.4 on 2025-01-02 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0009_alter_member_last_login'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='member',
            table='members',
        ),
    ]
